# ----------------------
# SIRH Backend Dev Profile
# ----------------------
spring:
  config:
    activate:
      on-profile: dev

  # ----------------------
  # Dev tools
  # ----------------------
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  # ----------------------
  # Datasource / PostgreSQL
  # ----------------------
  datasource:
    url: jdbc:postgresql://localhost:5432/sirh_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true                # Show SQL queries
    properties:
      hibernate.format_sql: true  # Format SQL nicely
      hibernate.use_sql_comments: true

# ----------------------
# Logging
# ----------------------
logging:
  level:
    root: INFO
    com.tarmiz.SIRH_backend: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

    # silence noisy packages
    sun.rmi: WARN
    javax.management: WARN
    com.zaxxer.hikari.pool: INFO
